services:
  solution-repository-postgres:
    image: postgres:16-alpine
    container_name: solution-repository-postgres
    environment:
      POSTGRES_DB: chart_repository
      POSTGRES_USER: chart_repository
      POSTGRES_PASSWORD: chart_repository
    ports:
      - "5433:5432"
    volumes:
      - solution-repository-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chart_repository -d chart_repository"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  solution-repository-postgres-data:
